### ISSUE TITLE
Is there a built-in python3 version?

### ISSUE THREAD

**Issue by onsunsl** [sillsdev/aeneas-installer#29]
Dear danielbair
Can you provide a built-in python3 version？ 
thanks

**Comment by danielbair** [comment]
I have not tried to build a python3 version.

**Comment by danielbair** [comment]
Ok. I am updating to Python 3.7 due to Python 2.7 reaching end of support by January 1, 2020.

You can try out the mac installer here... https://github.com/danielbair/aeneas-installer/releases/tag/v1.7.3.0_2m

**Comment by danielbair** [comment]
Windows and Mac installers with Python 3.7 can be found here...
https://github.com/sillsdev/aeneas-installer/releases/tag/v1.7.3.0_2
