### ISSUE TITLE
Linux Version

### ISSUE THREAD

**Issue by pietrop** [sillsdev/aeneas-installer#30]
First of all thank you so much for this! have used in on a mac and made it soo easy to 
install Aeneas.

I was wondering how complicated would it be to build a linux version of this?

**Comment by danielbair** [comment]
There is already a debian package for aeneas maintained by @chrisvire

**Comment by pietrop** [comment]
Thanks, do you have a link?

**Comment by chrisvire** [comment]
the debian package source is in the original source repository: https://github.com/readbeyond/aeneas

We have a build of the package at packages.sil.org (but an older version -- 1.5.0).  I am planning on updating the built package to 1.7.2 (to match what is published for Windows and Mac).

**Comment by pietrop** [comment]
Thanks @chrisvire !! Much appreciated :)
