### ISSUE TITLE
Win Installation Error: aeneas-1.7.3.0-cp27-cp27m-win32.whl is missing

### ISSUE THREAD

**Issue by braincoded** [sillsdev/aeneas-installer#32]
Hi there,
I've tried to install aeneas under Windows, however, after successfully running

`build_setup.bat`

the proceeding call of

`build_packages.bat`

isn't successful and gets aborted with an error:

Error on line 61 in D:\aeneas\aeneas-installer-master\MS_Windows_Installer\Aeneas_Installer.iss: Source file "D:\aeneas\aeneas-installer-master\MS_Windows_Installer\aeneas-1.7.3.0-cp27-cp27m-win32.whl" does not exist.
Compile aborted.

Can you give any advice how to solve this issue?

Thanks a lot!

**Comment by danielbair** [comment]
Hmmm. I sure thought I had tested this before uploading. I will check it out just now.

**Comment by danielbair** [comment]
Oh, you're trying to build the installer. I just tested the released prebuilt [installer](https://github.com/sillsdev/aeneas-installer/releases) and it is working fine.
I cannot guarantee that the build scripts work on all MS Windows configurations. With each aeneas release I have to manually update the build scripts.

**Comment by braincoded** [comment]
Thanks for mentioning the prebuilt installers! I had missed that part. Using those the Installation worked fine.
