### ISSUE TITLE
python `2.7` - `missing /usr/local/opt` 

### ISSUE THREAD

**Issue by pietrop** [sillsdev/aeneas-installer#33]
Hello, 
First, thank you soo much for making this!

I am using this `.dmg` for the users of the [`subtitlesComposer-app`](https://github.com/pietrop/subtitlesComposer-app) I have been working on. It's an electron app. And it uses [this module ](https://github.com/pietrop/subtitlesComposer ) to wrap around an aeneas system (terminal) call.

After installing the `.dmg` on some mac when calling aeneas I get an error saying for python `2.7` is missing under `/usr/local/opt/..` .

See screesnshot below

![screen shot 2018-06-08 at 10 23 06](https://user-images.githubusercontent.com/4661975/41463283-339b36f0-7096-11e8-8ae9-74fdcccf6285.png)

It seems like it's not possible to call aeneas as it cannot find the installation of python?

I was wondering if that's something you had encounter before?

**Comment by danielbair** [comment]
Did  you ever get this resolved? It should have installed python 2.7 but there may have been a permission issue with the latest macOS.

**Comment by pietrop** [comment]
Thanks @danielbair, only a through a "manual" workaround https://github.com/pietrop/subtitlesComposer-app/issues/1#issuecomment-417775982 by @bfasenfest

I think the OS at the time was, OS X High Sierra, 10.13.6

Curious what might be the permission issue with the latest macOS that you mentioned?

**Comment by danielbair** [comment]
This should be fixed with the latest installer for Mac
https://github.com/sillsdev/aeneas-installer/releases/tag/v1.7.3_1
