### ISSUE TITLE
Mac Installer missing amr_nb encoder

### ISSUE THREAD

**Issue by chrisvire** [sillsdev/aeneas-installer#35]
It looks like the version of ffmpeg that is included in the Mac Installer is missing the amr_nb encoder for creating 3gp files.  It looks like the installer is getting ffmpeg from Homebrew.  The newest version of ffmpeg (https://formulae.brew.sh/formula/ffmpeg) include amr_nb using opencore-amr library).

**Comment by danielbair** [comment]
Ok, I will look at rebuilding both the Mac and Windows installers.

**Comment by danielbair** [comment]
See the new Mac installer which includes ffmpeg 4.1.4
https://github.com/sillsdev/aeneas-installer/releases/tag/v1.7.3_1
