### ISSUE TITLE
MacOS installer not working on Catalina 10.15

### ISSUE THREAD

**Issue by donand** [sillsdev/aeneas-installer#44]
I downloaded and executed the latest .dmg installer (v 1.7.3.0_2) from https://github.com/sillsdev/aeneas-installer/releases but it gives me this error.

![image](https://user-images.githubusercontent.com/10143667/69858795-0c0ea400-1293-11ea-81c0-c228d6685d6e.png)

**Comment by danielbair** [comment]
Is this on macOS Catalina? I’ve only tested it up to macOS Mojave.

Are you running an anti virus software? I’ve never seen an error like this
before.

I will try to do some tests this weekend.

**Comment by danielbair** [comment]
For a short term solution to your problem: right click on
“aeneas-mac-setup-1.7.3.0_2.pkg” file and choose Open, then when the
message comes up again it will have an Open button and after you click that
it will install as usual.

**Comment by donand** [comment]
Hi @danielbair,
Yes, I'm on MacOS Catalina.

In the end I installed aeneas with brew and it worked.

Thanks for your help.

**Comment by danielbair** [comment]
Fixed via instructions at: https://www.kvraudio.com/forum/viewtopic.php?t=531663
