### ISSUE TITLE
Customze installation : not able to select packages

### ISSUE THREAD

**Issue by cladsam** [sillsdev/aeneas-installer#45]
Hello,

the packge do not allow to select what we want to install and what we woudl like to skip.
In my case I'm already having a newer version of python installed but I wasn't able to skip reinstalling it.

Best regards
M

**Comment by danielbair** [comment]
I am guessing you are referring to the Windows installer, as the Mac installer didn't have this restriction.
I am working on new 64-bit and 32-bit installers for Windows that will allow user selection of the packages installed.

**Comment by CatChenal** [comment]
Is it possible to install aenas using the Windows installer into an existing python 3.7 environment?

**Comment by danielbair** [comment]
If you already have a python 3.x environment setup, then maybe just use the all-in-one installer to install ffmpeg and espeak. Then use the python install instructions for installing aeneas. 
i.e.
pip install numy
pip install aeneas

**Comment by danielbair** [comment]
Latest installers allow full selection.
