### ISSUE TITLE
Expired certificate for macOS Installer

### ISSUE THREAD

**Issue by chrisvire** [sillsdev/aeneas-installer#50]
@danielbair, are you able to rebuild the installer with a newer certificate? I can get your an SIL certificate if you need one.

![Screenshot 2023-05-02 at 11 07 09](https://user-images.githubusercontent.com/517814/235683617-89a6674c-ddd6-47c9-9c0b-1330eb78e918.png)

**Comment by danielbair** [comment]
Yes. I will work on it. It looks like the Windows and Mac installers need some attention.

**Comment by chrisvire** [comment]
I will be at EMDC if you happen to be there this year.

**Comment by danielbair** [comment]
I'm working on this right now. I'm building on my Mac OS X virtual machine. The highest version of Python supported on 10.9 is Python 3.9 (the higher versions of Python all require macOS 11) so I will trust Python 3.9 is sufficient for most users.

**Comment by chrisvire** [comment]
Thanks @danielbair !

**Comment by danielbair** [comment]
I just uploaded v1.7.3.0_4 signed and notarized for Mac, but I am not able to sign the Windows installer.
